-- My Economy / Supabase database
-- Run this entire file in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.loans (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  start_sum numeric(14,2) not null check (start_sum >= 0),
  interest_rate numeric(6,3) not null check (interest_rate >= 0),
  amortization numeric(14,2) not null check (amortization >= 0),
  start_date date not null,
  created_at timestamptz not null default now()
);

create table if not exists public.loan_updates (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  loan_id bigint not null references public.loans(id) on delete cascade,
  updated_amortization numeric(14,2) not null check (updated_amortization >= 0),
  updated_interest_rate numeric(6,3) not null check (updated_interest_rate >= 0),
  update_date date not null,
  created_at timestamptz not null default now()
);

create table if not exists public.one_time_payments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  loan_id bigint not null references public.loans(id) on delete cascade,
  amount numeric(14,2) not null check (amount > 0),
  payment_date date not null,
  created_at timestamptz not null default now()
);

alter table public.loans enable row level security;
alter table public.loan_updates enable row level security;
alter table public.one_time_payments enable row level security;

drop policy if exists "Users can manage their own loans" on public.loans;
create policy "Users can manage their own loans" on public.loans
for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users can manage their own loan updates" on public.loan_updates;
create policy "Users can manage their own loan updates" on public.loan_updates
for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users can manage their own one time payments" on public.one_time_payments;
create policy "Users can manage their own one time payments" on public.one_time_payments
for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

create index if not exists loans_user_id_idx on public.loans(user_id);
create index if not exists loan_updates_loan_id_idx on public.loan_updates(loan_id);
create index if not exists one_time_payments_loan_id_idx on public.one_time_payments(loan_id);

-- IMPORTANT:
-- Your old MySQL/SQLite seed data cannot be inserted until you have a Supabase
-- user account, because user_id is required. After creating your account,
-- copy your UUID from the Setup page and use e.g.:
--
-- insert into public.loans (user_id,start_sum,interest_rate,amortization,start_date)
-- values ('YOUR-USER-UUID', 543755, 4.35, 0, '2024-07-20');
